Added documentation into NovelRT::Ecs.
novelrt/NovelRT pull request #252
Opened 2020-12-31 00:48 UTC by RubyNova

2021-01-02 14:37 UTC, capnkenny requested changes
Looks good! A couple spelling mistakes need fixing before this can be approved.

2021-01-02 14:37 UTC, capnkenny commented on include/NovelRT/Ecs/ComponentBuffer.h
> +         * @param poolSize The amount of worker threads being utilisied in this instance of the ECS.
Spelling mistake: utilising

2021-01-02 14:37 UTC, capnkenny commented on include/NovelRT/Ecs/EcsUtils.h
> +     * @tparam TComponent The component type to get he ID for.
Spelling mistake: the

2021-01-02 14:37 UTC, capnkenny commented on include/NovelRT/Ecs/EntityCache.h
> +         * @brief Propagates deletion requests from worker threads to the main thrad. Once this is called, the data can be accessed from EntityCache::GetEntitiesToRemoveThisFrame.
Spelling mistake: thread

2021-01-02 14:38 UTC, capnkenny commented on include/NovelRT/Ecs/ComponentBuffer.h
> +         * @param poolSize The amount of worker threads being utilisied in this instance of the ECS.
Sorry - `utilised`

2021-01-02 14:38 UTC, RubyNova commented on include/NovelRT/Ecs/ComponentBuffer.h
> +         * @param poolSize The amount of worker threads being utilisied in this instance of the ECS.
What's the typo here?

2021-01-02 14:39 UTC, RubyNova commented on include/NovelRT/Ecs/ComponentBuffer.h
> +         * @param poolSize The amount of worker threads being utilisied in this instance of the ECS.
Oh nevermind

2021-01-03 02:01 UTC, capnkenny approved these changes

2021-01-03 02:23 UTC, merged