Add resource loading support for audio files.
novelrt/NovelRT pull request #499
Opened 2022-09-09 23:21 UTC by RubyNova

2022-09-09 23:32 UTC, capnkenny requested changes
LGTM bar one issue with an exception message

2022-09-09 23:32 UTC, capnkenny commented on src/NovelRT/ResourceManagement/Desktop/DesktopResourceLoader.cpp
> +            throw NovelRT::Exceptions::FileNotFoundException(filePath.string());
Is this entirely true here? - the original logging would log the error message returned by sndfile (whether it was malformed file, wrong/unsupported format, etc) so we should probably do the same before throwing (or we include sndfile's error in the exception we throw)

2022-09-10 22:40 UTC, RubyNova commented
This PR is blocked until I can add interop support for resource loading APIs.

2022-10-23 17:21 UTC, capnkenny approved these changes
LGTM

2022-10-27 00:48 UTC, merged