Implement VMA usage and update APIs to reflect the simplification.
novelrt/NovelRT pull request #588
Opened 2023-07-02 02:48 UTC by RubyNova

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](https://github.com/novelrt/NovelRT/blob/misc/templates/Contributing.md#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This change will be a major rework of important graphics concepts.

**Is there an open issue that this resolves? If so, please [link it here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).**
No.

**What is the current behavior?** (You can also link to an open issue here)
the legacy API exists and makes everyone cry.

**What is the new behavior (if this is a feature change)?**
The new API and VMA support will make less people cry.

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Yes. RIP Anything that's predefined ECS based for a little bit in interop.

**Other information**:
This PR was sponsored by Padme's very dubious choice in a life partner.

2023-07-02 02:49 UTC, FiniteReality commented
:man: :woman: :child: :child: :child: :child: :skull:

2023-07-02 02:51 UTC, FiniteReality commented
Related: #583

2025-05-15 17:31 UTC, RubyNova commented
PR is ready, we will be rebasing it from changes in main before final submission.

2025-05-16 16:59 UTC, capnkenny requested changes
Some formatting stuff, but otherwise good so far - got a few questions as well.

I'm going to work under the assumption here that at some point you will be restoring the samples? If not, we should discuss in the 'cord

2025-05-16 16:59 UTC, capnkenny commented on Graphics/Core/include/NovelRT/Graphics/GraphicsBackendTraits.hpp
> +}
Nit: no EOL?

2025-05-16 16:59 UTC, capnkenny commented on Graphics/Core/include/NovelRT/Graphics/GraphicsCmdList.hpp
> +    };
Are you still moving this?

2025-05-16 16:59 UTC, capnkenny commented on Graphics/Core/include/NovelRT/Graphics/GraphicsPipelineInput.hpp
> +#include <NovelRT/Graphics/GraphicsPipelineInputElement.hpp>
Should these get flipped? I'm not sure if we have a well-defined pattern, but other files previously did:
```cpp
#include <NovelRT/blah/blah.h>
#include <vector>
```
(As an example, we have been putting NovelRT references before stdlib and others)

2025-05-16 16:59 UTC, capnkenny commented on Graphics/Core/include/NovelRT/Graphics/GraphicsResource.hpp
> +        //[[nodiscard]] virtual size_t GetAlignment() const noexcept = 0; //TODO: Do we still need this?
Nope, probably don't need this anymore do we?

2025-05-16 16:59 UTC, capnkenny commented on Graphics/Core/include/NovelRT/Graphics/GraphicsTextureCreateInfo.hpp
> +}
Nit: love me some missing EOFs

2025-05-16 16:59 UTC, capnkenny commented on Graphics/Vulkan/VulkanGraphicsAdapterSelector.cpp
> +#include <NovelRT/Graphics/Vulkan/Utilities/Support.hpp>
U stil wana clean dis up, m8?

2025-05-16 16:59 UTC, capnkenny commented on Graphics/Vulkan/VulkanGraphicsBackendTraits.cpp
> +//template class NovelRT::Graphics::GraphicsResourceMemoryRegion<NovelRT::Graphics::Vulkan::VulkanGraphicsBackend>;
Needed? Unnecessary?

2025-05-16 16:59 UTC, capnkenny commented on Graphics/Vulkan/VulkanGraphicsBuffer.cpp
> +            throw std::runtime_error("Failed to map Vulkan memory to the CPU. Reason: " + std::to_string(result));
You still have time, it wants to be a _real_ exception :)

2025-05-16 16:59 UTC, capnkenny commented on Graphics/Vulkan/VulkanGraphicsBuffer.cpp
> +            throw std::runtime_error("Failed to invalidate mapped memory. Reason: " + std::to_string(mapResult));
Same here, unless we don't care at the moment. Exceptions don't have feelings...

2025-05-16 16:59 UTC, capnkenny commented on Graphics/Vulkan/VulkanGraphicsCmdList.cpp
> +    {
Um... is this cursed formatting? Or is it just GH being funny?
Something has sent clearValues to the right side of the screen LMAO
![image](https://github.com/user-attachments/assets/e5518eb8-eb44-4e61-aa30-c64a93e838fc)

2025-05-16 16:59 UTC, capnkenny commented on Graphics/Vulkan/VulkanGraphicsContext.cpp
> +
Whaaaaaaatcha doooooiiiiin hereeeeeee?

2025-05-16 16:59 UTC, capnkenny commented on Graphics/Vulkan/VulkanGraphicsContext.cpp
> +//    }
I cry every time my browser freezes seeing these leftover comments lol

2025-05-16 16:59 UTC, capnkenny commented on Graphics/Vulkan/VulkanGraphicsMemoryAllocator.cpp
> +                                               // fairly sure we need it. Lol.
OMEGALUL
(Feel free to close this lol)

2025-05-16 16:59 UTC, capnkenny commented on Graphics/Vulkan/VulkanGraphicsMemoryAllocator.cpp
> +        // allocationCreateInfo.priority = 1; //TODO: do I need this?
You should need this if we need to prioritize the allocation over others. If everything is "de-prioritized", then no - simply don't set it or default it to 0.

2025-05-16 16:59 UTC, capnkenny commented on Graphics/Vulkan/VulkanGraphicsPluginProvider.cpp
> +}
Nit: EOL

2025-05-16 16:59 UTC, capnkenny commented on Graphics/Vulkan/VulkanGraphicsPluginProvider.cpp
> +}
Could we maybe... unfuck these now? Or are they just cursed but guaranteed to work? If that's the case, I'm okay with deferring, just the comments seem... nefarious.

2025-05-16 16:59 UTC, capnkenny commented on Graphics/Vulkan/VulkanGraphicsRenderPass.cpp
> +}
GitHub lags and doesn't auto-open the comment section _every time i happen to stumble on an EOL issue_. It's pretty funny actually, lol

2025-05-16 17:00 UTC, RubyNova commented on Graphics/Core/include/NovelRT/Graphics/GraphicsCmdList.hpp
> +    };
In a later submission, yes. This PR is just so old however and we still have bugs to fix, I want to get this submitted to unblock fixing some bugs and getting progress on some other tasks.

2025-05-16 17:00 UTC, RubyNova commented on Graphics/Core/include/NovelRT/Graphics/GraphicsPipelineInput.hpp
> +#include <NovelRT/Graphics/GraphicsPipelineInputElement.hpp>
uhhhh clang-format should have re-arranged these at some point? I can try to verify if you want.

2025-05-16 17:01 UTC, RubyNova commented on Graphics/Core/include/NovelRT/Graphics/GraphicsResource.hpp
> +        //[[nodiscard]] virtual size_t GetAlignment() const noexcept = 0; //TODO: Do we still need this?
It's not come up so most likely not.

2025-05-16 17:02 UTC, RubyNova commented on Graphics/Vulkan/VulkanGraphicsBackendTraits.cpp
> +//template class NovelRT::Graphics::GraphicsResourceMemoryRegion<NovelRT::Graphics::Vulkan::VulkanGraphicsBackend>;
unsure, cc @FiniteReality

2025-05-16 17:02 UTC, RubyNova commented on Graphics/Vulkan/VulkanGraphicsCmdList.cpp
> +    {
it's not doing that on my monitor?

2025-05-16 17:03 UTC, RubyNova commented on Graphics/Vulkan/VulkanGraphicsContext.cpp
> +
This is the old API. I kept it around for reference while working on the new cmdlist API. We can most likely delete this now.

2025-05-16 17:04 UTC, RubyNova commented on Graphics/Vulkan/VulkanGraphicsMemoryAllocator.cpp
> +                                               // fairly sure we need it. Lol.
:Sunglas

2025-05-16 17:04 UTC, RubyNova commented on Graphics/Vulkan/VulkanGraphicsMemoryAllocator.cpp
> +        // allocationCreateInfo.priority = 1; //TODO: do I need this?
This is for future me to figure out I reckon, not for this PR.

2025-05-16 17:05 UTC, RubyNova commented on Graphics/Vulkan/VulkanGraphicsPluginProvider.cpp
> +}
This is because of the changes we made to how the graphics plugin was loaded. Comments are still relevant but code itself is perfectly safe and works as intended for the time being.

2025-05-16 17:36 UTC, capnkenny commented on Graphics/Core/include/NovelRT/Graphics/GraphicsPipelineInput.hpp
> +#include <NovelRT/Graphics/GraphicsPipelineInputElement.hpp>
If CI isn't really complaining, then I guess it's okay

2025-05-16 17:55 UTC, RubyNova commented on Graphics/Core/include/NovelRT/Graphics/GraphicsPipelineInput.hpp
> +#include <NovelRT/Graphics/GraphicsPipelineInputElement.hpp>
Looks like CI clang-format didn't catch this one, my local clang-format did. Thanks!

2025-05-16 18:01 UTC, RubyNova commented on Graphics/Vulkan/VulkanGraphicsBuffer.cpp
> +            throw std::runtime_error("Failed to invalidate mapped memory. Reason: " + std::to_string(mapResult));
So I have attempted to do this, however I think this is part of a broader conversation we need to have about asserts vs exceptions in some parts of the graphics API, and what we'd like to do, so I'm going to leave this alone for now.

2025-05-16 18:09 UTC, capnkenny approved these changes
LGTM!

2025-05-16 18:09 UTC, merged