Fix spdlog issue and numerous GHActions deprecation warnings
novelrt/NovelRT pull request #601
Opened 2024-04-14 11:30 UTC by capnkenny

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](https://github.com/novelrt/NovelRT/blob/misc/templates/Contributing.md#pull-requests)
- [N/A] Tests for the changes have been added (for bug fixes / features)
- [N/A] Documentation has been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fixes a build error induced by spdlog and newer versions of MSVC, and resolves some GH Actions warnings about node12/node16 deprecation.

**Is there an open issue that this resolves? If so, please [link it here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).**
Fixes #600 

**What is the current behavior?** (You can also link to an open issue here)
Builds fail when attempting to compile `NovelRT-Graphics` due to iterator usage from spdlog that is deprecated - this is due to older `fmt` builds built into spdlog that use the old behavior.

2024-04-30 22:51 UTC, RubyNova requested changes

2024-04-30 22:51 UTC, RubyNova commented on thirdparty/fmt/CMakeLists.txt
> +set_property(TARGET fmt PROPERTY POSITION_INDEPENDENT_CODE ON)
Missing EOL

2024-05-20 23:04 UTC, capnkenny commented on thirdparty/fmt/CMakeLists.txt
> +set_property(TARGET fmt PROPERTY POSITION_INDEPENDENT_CODE ON)
Think it's gone now

2024-05-21 01:11 UTC, RubyNova approved these changes
LGTm

2024-05-21 02:25 UTC, merged